# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"

    filter_sets:
        squared_output_medium:
            filters:
                thumbnail:
                    size: [350, 350]
                    mode: outbound
                    allow_upscale: true

                    
    
        squared_output_small:
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
                    allow_upscale: true

        rounded_output_medium:
            filters:
                thumbnail:
                    size: [150, 150]
                    mode: outbound